name: 'Label Validator'
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  require-pull-request-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          expectedLabels: 'release*'
